# Generated by Django 2.2.6 on 2021-03-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0017_visit_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updater', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('name', models.CharField(max_length=100, verbose_name='用例集名称')),
                ('url', models.CharField(max_length=255, verbose_name='请求地址')),
                ('step', models.IntegerField(verbose_name='顺序')),
                ('case', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Case')),
            ],
            options={
                'verbose_name': '用例信息 Step',
                'db_table': 'test_suite_step',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updater', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('name', models.CharField(max_length=100, verbose_name='用例集名称')),
                ('relation', models.IntegerField(verbose_name='节点id')),
                ('length', models.IntegerField(verbose_name='Case个数')),
                ('tag', models.IntegerField(choices=[(1, '冒烟用例集'), (2, '集成用例集'), (3, '监控脚本')], default=2, verbose_name='用例集标签')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Project')),
            ],
            options={
                'verbose_name': '用例集',
                'db_table': 'test_suite',
            },
        ),
    ]
